09-07 09:02:08 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: テーブル "PLAY_EVOLUTIONS" が見つかりません
Table "PLAY_EVOLUTIONS" not found; SQL statement:
select id, hash, apply_script, revert_script, state, last_problem from play_evolutions where state like 'applying_%' [42102-172]
09-07 10:02:17 jdbc[31]: exception
org.h2.jdbc.JdbcSQLException: テーブル "ARTICLES" はすでに存在します
Table "ARTICLES" already exists; SQL statement:
create table articles (
id	bigint not null,
title	varchar(255) not null,
body	text not null,
release	date not null,
primary key(id),
) [42101-172]
09-07 10:02:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "ARTICLES" はすでに存在します
Table "ARTICLES" already exists; SQL statement:
create table articles (
id	bigint not null,
title	varchar(255) not null,
body	text not null,
release	date not null,
primary key(id),
) [42101-172]
09-07 10:03:05 jdbc[31]: exception
org.h2.jdbc.JdbcSQLException: テーブル "ARTICLES" はすでに存在します
Table "ARTICLES" already exists; SQL statement:
create table articles (
id	bigint not null,
title	varchar(255) not null,
body	text not null,
release	date not null,
primary key(id),
) [42101-172]
09-07 10:03:20 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: テーブル "ARTICLES" はすでに存在します
Table "ARTICLES" already exists; SQL statement:
create table articles (
id	bigint not null,
title	varchar(255) not null,
body	text not null,
release	date not null,
primary key(id),
) [42101-172]
09-07 10:06:58 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: テーブル "ARTICLES" はすでに存在します
Table "ARTICLES" already exists; SQL statement:
create table articles (
id                        bigint not null,
username                  varchar(255),
password                  varchar(255),
constraint pk_articles primary key (id)) [42101-172]
09-07 10:08:35 jdbc[17]: exception
org.h2.jdbc.JdbcSQLException: SQLステートメントに文法エラーがあります "SELECT ACCOUNTS_SEQ.NEXTVAL UNION[*] SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL "; 期待されるステートメント "identifier"
Syntax error in SQL statement "SELECT ACCOUNTS_SEQ.NEXTVAL UNION[*] SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL "; expected "identifier"; SQL statement:
select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval [42001-172]
09-07 10:08:47 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: SQLステートメントに文法エラーがあります "SELECT ACCOUNTS_SEQ.NEXTVAL UNION[*] SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL "; 期待されるステートメント "identifier"
Syntax error in SQL statement "SELECT ACCOUNTS_SEQ.NEXTVAL UNION[*] SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL UNION SELECT ACCOUNTS_SEQ.NEXTVAL "; expected "identifier"; SQL statement:
select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval union select accounts_seq.nextval [42001-172]
09-07 10:10:06 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: テーブル "ARTICLES" はすでに存在します
Table "ARTICLES" already exists; SQL statement:
create table articles (
id	bigint not null,
title	varchar(255) not null,
body	text not null,
release	date not null,
primary key(id),
) [42101-172]
09-07 10:14:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "ARTICLES" はすでに存在します
Table "ARTICLES" already exists; SQL statement:
create table articles (
id	bigint not null,
title	varchar(255) not null,
body	text not null,
release	date not null,
primary key(id),
) [42101-172]
09-07 10:15:27 jdbc[45]: exception
org.h2.jdbc.JdbcSQLException: テーブル "ARTICLES" はすでに存在します
Table "ARTICLES" already exists; SQL statement:
create table articles (
id	bigint not null,
title	varchar(255) not null,
body	text not null,
release	date not null,
primary key(id),
) [42101-172]
09-07 10:15:32 jdbc[70]: null
org.h2.message.DbException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at play.utils.ProxyDriver.connect(ProxyDriver.scala:9)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:351)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:245)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:243)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at play.api.db.BoneCPPlugin.onStart(DB.scala:243)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
	at play.api.Play$.start(Play.scala:87)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112)
	at scala.Option.map(Option.scala:145)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110)
	at scala.util.Success.flatMap(Try.scala:200)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.h2.jdbc.JdbcSQLException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 44 more
