2015-12-16 11:14:22,172 - [INFO] - from play in pool-6-thread-3 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000

2015-12-16 11:15:04,860 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:file:play

2015-12-16 11:15:06,480 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2015-12-16 11:15:22,229 - [ERROR] - from play in play-internal-execution-context-1 
Cannot invoke the action, eventually got an error: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

2015-12-16 11:15:22,276 - [ERROR] - from application in play-internal-execution-context-1 


! @6oef72m8e - Internal server error, for (POST) [/authenticate] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.reflect.InvocationTargetException]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.6.jar:2.2.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:268) [play_2.10-2.2.6.jar:2.2.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:268) [play_2.10-2.2.6.jar:2.2.6]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:268) [play_2.10-2.2.6.jar:2.2.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at play.data.Form.bind(Form.java:392) ~[play-java_2.10-2.2.6.jar:2.2.6]
	at play.data.Form.bindFromRequest(Form.java:216) ~[play-java_2.10-2.2.6.jar:2.2.6]
	at controllers.Application.authenticate(Application.java:142) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$20$$anonfun$apply$20.apply(routes_routing.scala:297) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$20$$anonfun$apply$20.apply(routes_routing.scala:297) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.GlobalSettings$1.call(GlobalSettings.java:64) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.filters.csrf.RequireCSRFCheckAction.call(RequireCSRFCheckAction.java:51) ~[filters-helpers_2.10-2.2.6.jar:2.2.6]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10-2.2.6.jar:2.2.6]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10-2.2.0.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10-2.2.0.jar:2.2.0]
	... 4 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at play.data.Form.bind(Form.java:389) ~[play-java_2.10-2.2.6.jar:2.2.6]
	... 23 common frames omitted
Caused by: javax.persistence.PersistenceException: Unique expecting 0 or 1 rows but got [3]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findUnique(DefaultServer.java:1236) ~[avaje-ebeanorm-3.2.2.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findUnique(DefaultOrmQuery.java:903) ~[avaje-ebeanorm-3.2.2.jar:na]
	at com.avaje.ebeaninternal.util.DefaultExpressionList.findUnique(DefaultExpressionList.java:193) ~[avaje-ebeanorm-3.2.2.jar:na]
	at models.Login.authenticate(Login.java:29) ~[na:na]
	at models.Login.validate(Login.java:14) ~[na:na]
	... 28 common frames omitted

2015-12-16 11:23:58,512 - [INFO] - from play in play-internal-execution-context-18 
database [default] connected at jdbc:h2:file:play

2015-12-16 11:23:58,850 - [INFO] - from play in play-internal-execution-context-18 
Application started (Dev)

2015-12-16 11:28:56,795 - [INFO] - from play in play-internal-execution-context-20 
database [default] connected at jdbc:h2:file:play

2015-12-16 11:28:57,199 - [INFO] - from play in play-internal-execution-context-20 
Application started (Dev)

2015-12-16 11:30:41,817 - [INFO] - from play in play-internal-execution-context-20 
database [default] connected at jdbc:h2:file:play

2015-12-16 11:30:42,094 - [INFO] - from play in play-internal-execution-context-20 
Application started (Dev)

2015-12-16 11:41:52,608 - [INFO] - from play in play-internal-execution-context-20 
database [default] connected at jdbc:h2:file:play

2015-12-16 11:41:52,815 - [INFO] - from play in play-internal-execution-context-20 
Application started (Dev)

2015-12-16 11:43:46,740 - [ERROR] - from play in play-internal-execution-context-23 
Cannot invoke the action, eventually got an error: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

2015-12-16 11:43:46,760 - [ERROR] - from application in play-internal-execution-context-23 


! @6oefalljp - Internal server error, for (POST) [/authenticate] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.reflect.InvocationTargetException]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.6.jar:2.2.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:268) [play_2.10-2.2.6.jar:2.2.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:268) [play_2.10-2.2.6.jar:2.2.6]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:268) [play_2.10-2.2.6.jar:2.2.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at play.data.Form.bind(Form.java:392) ~[play-java_2.10-2.2.6.jar:2.2.6]
	at play.data.Form.bindFromRequest(Form.java:216) ~[play-java_2.10-2.2.6.jar:2.2.6]
	at controllers.Application.authenticate(Application.java:142) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$20$$anonfun$apply$20.apply(routes_routing.scala:297) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$20$$anonfun$apply$20.apply(routes_routing.scala:297) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.GlobalSettings$1.call(GlobalSettings.java:64) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.filters.csrf.RequireCSRFCheckAction.call(RequireCSRFCheckAction.java:51) ~[filters-helpers_2.10-2.2.6.jar:2.2.6]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10-2.2.6.jar:2.2.6]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10-2.2.0.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10-2.2.0.jar:2.2.0]
	... 4 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at play.data.Form.bind(Form.java:389) ~[play-java_2.10-2.2.6.jar:2.2.6]
	... 23 common frames omitted
Caused by: javax.persistence.PersistenceException: Unique expecting 0 or 1 rows but got [2]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findUnique(DefaultServer.java:1236) ~[avaje-ebeanorm-3.2.2.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findUnique(DefaultOrmQuery.java:903) ~[avaje-ebeanorm-3.2.2.jar:na]
	at com.avaje.ebeaninternal.util.DefaultExpressionList.findUnique(DefaultExpressionList.java:193) ~[avaje-ebeanorm-3.2.2.jar:na]
	at models.Login.authenticate(Login.java:29) ~[na:na]
	at models.Login.validate(Login.java:14) ~[na:na]
	... 28 common frames omitted

2015-12-16 12:05:53,523 - [INFO] - from play in play-internal-execution-context-23 
database [default] connected at jdbc:h2:file:play

2015-12-16 12:05:54,126 - [INFO] - from play in play-internal-execution-context-23 
Application started (Dev)

2015-12-16 15:11:01,021 - [INFO] - from play in play-internal-execution-context-30 
database [default] connected at jdbc:h2:file:play

2015-12-16 15:11:01,555 - [INFO] - from play in play-internal-execution-context-30 
Application started (Dev)

2015-12-16 15:21:03,550 - [INFO] - from play in play-internal-execution-context-35 
database [default] connected at jdbc:h2:file:play

2015-12-16 15:21:03,894 - [INFO] - from play in play-internal-execution-context-35 
Application started (Dev)

2015-12-16 15:29:26,784 - [ERROR] - from application in New I/O worker #8 


! @6oegec59c - Internal server error, for (GET) [/edit_call] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value httlLine]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2015-12-16 15:29:50,121 - [INFO] - from play in play-internal-execution-context-35 
database [default] connected at jdbc:h2:file:play

2015-12-16 15:29:50,289 - [INFO] - from play in play-internal-execution-context-35 
Application started (Dev)

2015-12-16 15:30:58,769 - [INFO] - from play in play-internal-execution-context-38 
database [default] connected at jdbc:h2:file:play

2015-12-16 15:30:59,020 - [INFO] - from play in play-internal-execution-context-38 
Application started (Dev)

2015-12-16 15:35:45,356 - [ERROR] - from application in New I/O worker #6 


! @6oegf7jab - Internal server error, for (GET) [/edit_call] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value controller]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2015-12-16 15:37:00,890 - [ERROR] - from application in New I/O worker #6 


! @6oegfc13j - Internal server error, for (GET) [/edit_call] ->

play.PlayExceptions$CompilationException: Compilation error[value Appication is not a member of object controllers.routes]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2015-12-16 15:37:15,442 - [INFO] - from play in play-internal-execution-context-39 
database [default] connected at jdbc:h2:file:play

2015-12-16 15:37:15,744 - [INFO] - from play in play-internal-execution-context-39 
Application started (Dev)

2015-12-16 15:37:46,533 - [INFO] - from play in play-internal-execution-context-39 
database [default] connected at jdbc:h2:file:play

2015-12-16 15:37:46,614 - [INFO] - from play in play-internal-execution-context-39 
Application started (Dev)

2015-12-16 15:39:28,208 - [INFO] - from play in play-internal-execution-context-42 
database [default] connected at jdbc:h2:file:play

2015-12-16 15:39:28,396 - [INFO] - from play in play-internal-execution-context-42 
Application started (Dev)

2015-12-16 15:43:04,573 - [INFO] - from play in play-internal-execution-context-43 
database [default] connected at jdbc:h2:file:play

2015-12-16 15:43:04,803 - [INFO] - from play in play-internal-execution-context-43 
Application started (Dev)

2015-12-16 15:43:21,967 - [INFO] - from play in play-internal-execution-context-45 
database [default] connected at jdbc:h2:file:play

2015-12-16 15:43:22,051 - [INFO] - from play in play-internal-execution-context-45 
Application started (Dev)

2015-12-16 15:44:18,017 - [INFO] - from play in play-internal-execution-context-46 
database [default] connected at jdbc:h2:file:play

2015-12-16 15:44:18,175 - [INFO] - from play in play-internal-execution-context-46 
Application started (Dev)

2015-12-16 15:48:44,595 - [INFO] - from play in play-internal-execution-context-47 
database [default] connected at jdbc:h2:file:play

2015-12-16 15:48:44,942 - [INFO] - from play in play-internal-execution-context-47 
Application started (Dev)

2015-12-16 15:57:47,167 - [INFO] - from play in play-internal-execution-context-47 
database [default] connected at jdbc:h2:file:play

2015-12-16 15:57:47,364 - [INFO] - from play in play-internal-execution-context-47 
Application started (Dev)

2015-12-16 15:59:27,459 - [INFO] - from play in play-internal-execution-context-47 
database [default] connected at jdbc:h2:file:play

2015-12-16 15:59:27,687 - [INFO] - from play in play-internal-execution-context-47 
Application started (Dev)

2015-12-16 15:59:57,559 - [INFO] - from play in play-internal-execution-context-47 
database [default] connected at jdbc:h2:file:play

2015-12-16 15:59:57,682 - [INFO] - from play in play-internal-execution-context-47 
Application started (Dev)

2015-12-16 16:00:43,219 - [INFO] - from play in play-internal-execution-context-48 
database [default] connected at jdbc:h2:file:play

2015-12-16 16:00:43,410 - [INFO] - from play in play-internal-execution-context-48 
Application started (Dev)

2015-12-16 16:07:19,271 - [INFO] - from play in play-internal-execution-context-48 
database [default] connected at jdbc:h2:file:play

2015-12-16 16:07:19,584 - [INFO] - from play in play-internal-execution-context-48 
Application started (Dev)

